# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Kording lab's blog"
title:              "blog for kording lab"
description:        "this is a blog page for kording lab"


# URL
url:                http://kordinglab.github.io
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter: rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "blog"
    href:           "/blog"
  - name:           "people"
    href:           "/people"
  - name:           "reference"
    href:           "/reference"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"

collections:
  people:
    output: true
    permalink: /people/:title/index.html
